//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace craftersmine.Valknut.Launcher.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("craftersmine.Valknut.Launcher.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client ID: {0}.
        /// </summary>
        public static string AboutBox_Label_ClientId {
            get {
                return ResourceManager.GetString("AboutBox.Label.ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer: {0}.
        /// </summary>
        public static string AboutBox_Label_Developer {
            get {
                return ResourceManager.GetString("AboutBox.Label.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Header_Menu_AboutMenu {
            get {
                return ResourceManager.GetString("Header.Menu.AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string Header_Menu_LogoutMenu {
            get {
                return ResourceManager.GetString("Header.Menu.LogoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Header_Menu_SettingsMenu {
            get {
                return ResourceManager.GetString("Header.Menu.SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloaded: {0}% {1:F2} MB/{2:F2} MB.
        /// </summary>
        public static string InitializingFrame_Label_Progress {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checking Minecraft....
        /// </summary>
        public static string InitializingFrame_Label_Status_CheckingMinecraft {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.Status.CheckingMinecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading file....
        /// </summary>
        public static string InitializingFrame_Label_Status_DowloadingFile {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.Status.DowloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading Java....
        /// </summary>
        public static string InitializingFrame_Label_StatusOverall_DownloadingJava {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.StatusOverall.DownloadingJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading Minecraft....
        /// </summary>
        public static string InitializingFrame_Label_StatusOverall_DownloadingMinecraft {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.StatusOverall.DownloadingMinecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing Minecraft....
        /// </summary>
        public static string InitializingFrame_Label_StatusOverall_InitializingMinecraft {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.StatusOverall.InitializingMinecraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tip.
        /// </summary>
        public static string InitializingFrame_Label_TipTitle {
            get {
                return ResourceManager.GetString("InitializingFrame.Label.TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LoginFrame_Button_Login {
            get {
                return ResourceManager.GetString("LoginFrame.Button.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string LoginFrame_Button_Register {
            get {
                return ResourceManager.GetString("LoginFrame.Button.Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember Me.
        /// </summary>
        public static string LoginFrame_CheckBox_RememberMe {
            get {
                return ResourceManager.GetString("LoginFrame.CheckBox.RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail.
        /// </summary>
        public static string LoginFrame_TextBox_Email {
            get {
                return ResourceManager.GetString("LoginFrame.TextBox.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ex. example@example.com.
        /// </summary>
        public static string LoginFrame_TextBox_Email_Tip {
            get {
                return ResourceManager.GetString("LoginFrame.TextBox.Email.Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string LoginFrame_TextBox_Password {
            get {
                return ResourceManager.GetString("LoginFrame.TextBox.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Message_Error_Title {
            get {
                return ResourceManager.GetString("Message.Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Launch.
        /// </summary>
        public static string PlayFrame_Button_Launch {
            get {
                return ResourceManager.GetString("PlayFrame.Button.Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string PlayFrame_ClientDescription {
            get {
                return ResourceManager.GetString("PlayFrame.ClientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome back, {0}.
        /// </summary>
        public static string PlayFrame_WelcomeBox {
            get {
                return ResourceManager.GetString("PlayFrame.WelcomeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail field cannot be empty.
        /// </summary>
        public static string Validation_Email_FieldCannotBeEmpty {
            get {
                return ResourceManager.GetString("Validation.Email.FieldCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is not valid E-mail address, ex. example@example.com.
        /// </summary>
        public static string Validation_Email_FieldContentsIsNotEmail {
            get {
                return ResourceManager.GetString("Validation.Email.FieldContentsIsNotEmail", resourceCulture);
            }
        }
    }
}
